### PR TITLE
fix: render submodules in html docs

### LINKED ISSUE #1235: The HTML docs do not render submodules
The HTML docs currently does not render symbols in submodules (ie: [Dynamic.String](https://carp-lang.github.io/carp-docs/core/Dynamic.html#String)).

### PR DESCRIPTION
**Pull request by hellerve**
This PR fixes #1235 by adding submodules to the rendered docs. It achieves this by looking at "dependencies" (i.e. inner modules) and rendering them in the HTML in two places: inside the module as a link, and in the sidebar as a submenu.

Cheers

### CODE REVIEW

**Comment by TimDeve** [comment]
Looks good 👍

**Comment by hellerve** [comment]
@TimDeve good catch of me slacking off, should work now!

**Comment by TimDeve** [comment]
Thanks 😊

File: src/RenderDocs.hs [hunk 1]
```diff
@@ -37,16 +37,33 @@ saveDocsForEnvs ctx pathsAndEnvBinders =
...
+        mapM_ (saveDocsForEnvBinder ctx allEnvNames) pathsAndEnvBinders'
         when
           generateIndex
           ( writeFile
               (dir </> title ++ "_index.html")
               (projectIndexPage ctx allEnvNames)
           )
         putStrLn ("Generated docs to '" ++ dir ++ "'")
+  where
+    getDependenciesForEnvs = Prelude.concat . Prelude.map getEnvDependencies
```
Comment (scolsen) [inline src/RenderDocs.hs:53]: If you want, you could also import `Env` and likely use some combination of `findModules`, `envPublicBindingNames`, or something similar for the getDependencies part.

**Comment by hellerve** [comment]
Interesting, it looks fine to me. What browser are you using?

**Comment by hellerve** [comment]
> Maybe the module prefixes could be stripped to make the names shorter, so that they fit better?

Good idea! The module prefixes are removed now :)

**Comment by TimDeve** [comment]
Prefixes are still showing for me.

**Comment by eriksvedang** [comment]
> Prefixes are still showing for me.

It works for me (and looks much nicer!)

SDL docs are still weird. I'm on Firefox, looks similarly in Safari and Chrome though.

**Comment by TimDeve** [comment]
Thanks Veit.
