### PR TITLE
reorganize Pattern library

### LINKED ISSUE #1255: error in Pattern.split
This works just fine:
```
> (Pattern.global-match #"'.-'" "Whatever we 'do' is going to cause some 'trouble' no matter...")
[[@"'do'"] [@"'trouble'"]]
```

... however Patter.split fails for the same input:
```
> (Pattern.split        #"'.-'" "Whatever we 'do' is going to cause some 'trouble' no matter...")
Assertion failed!

Program: D:\tmp\bastel\docs-html\out\Untitled.exe
File: out\main.c, Line 4857

Expression: n < a.len
[RUNTIME ERROR] 'out\Untitled' exited with return value 3.
>
```

### PR DESCRIPTION
**Pull request by guberathome**
* feat!: Pattern.match now returns start and end indizes of the first match
* feat!: matches from Pattern.find-all can no longer overlap. This fixes #1255.
* feat!: Pattern.global-match-str now returns all matches as String 
* feat!: renamed (Pattern.global-match) to (Pattern.match-all-groups) 
* feat: implemented (Pattern.match-from)
* feat: moved Pattern.match-str and Pattern.find from C to Carp code 
* fix: moved some matching code from C to Carp and removed dead C functions

### CODE REVIEW

File: core/Pattern.carp [hunk 1]
```diff
@@ -1,6 +1,15 @@
 (system-include "carp_pattern.h")
 
 (defmodule Pattern
+  (register-type MatchResult "PatternMatchResult" [start Int, end Int])
+  (defn       match2str [match-res] 
+	(fmt "#<MatchResult start=%d end=%d>" 
+	  (MatchResult.start match-res) 
+	  (MatchResult.end   match-res) ))
+  (implements str Pattern.match2str)
```
Comment (hellerve) [inline core/Pattern.carp:9]: The convention here would be to do

```clojure
(defmodule MatchResult
  (defn str [match-res]
    ; your code
  )
  (implements str PatternMatchResult.str)
)
```

in a nested module, unless `str` clashes with anything.

**Comment by guberathome** [comment]
What is the purpose of having ```(Pattern.global-match-str)``` _and_ ```(Pattern.global-match)```? 
Is it to match _all_ Groups??
Could we remove or rename ```(Pattern.global-match)```?

```
> (Pattern.global-match-str   #"'.-'" "Whatever we 'do' is going to cause some 'trouble' no matter...")
[@"'do'" @"'trouble'"]
> (Pattern.global-match   #"'.-'" "Whatever we 'do' is going to cause some 'trouble' no matter...")
[[@"'do'"] [@"'trouble'"]]
```

File: core/Pattern.carp (hunk 1 above)
Comment (guberathome) [reply core/Pattern.carp]: Thank you for the pointer, updated the sources.

Printing a MatchResult in the REPL works, but printing (Array.MatchResult) does not.
What am I missing?
```
> (info Pattern.MatchResult.refstr)
Pattern.MatchResult.refstr : (Fn [(Ref Pattern.MatchResult a)] String)
  Defined at line 8, column 6 in '/home/ptokremin/contrib_ghub/Carp/core/Pattern.carp'
  Implements: (prn str)
> (info Pattern.MatchResult.str)
Pattern.MatchResult.str : (Fn [Pattern.MatchResult] String)
  Defined at line 16, column 6 in '/home/ptokremin/contrib_ghub/Carp/core/Pattern.carp'
  Documentation: converts a `Pattern.MatchResult` to a string.
  Implements: (prn str)
> (Pattern.match    #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
(MatchResult start=12 end=22)
> (info Pattern.find-all-matches )
Pattern.find-all-matches : (Fn [(Ref Pattern a), (Ref String b)] (Array Pattern.MatchResult))
  Defined at line 47, column 4 in '/home/ptokremin/contrib_ghub/Carp/core/Pattern.carp'
> (Pattern.find-all-matches     #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[Warning] No 'prn' function found with type (Fn [Pattern.MatchResult] String).
carp: Can't find any 'prn' function for member 'Inside array.' of type (Fn [Pattern.MatchResult] String)
CallStack (from HasCallStack):
  error, called at src/ArrayTemplates.hs:634:33 in CarpHask-0.5.1.0-EudeCbDnX8j3pnSP31uN8I:ArrayTemplates
```

Comment (hellerve) [reply core/Pattern.carp]: No, the `prn` function required here is of type `(Fn [Pattern.MatchResult] String)`. You defined one of type `(Fn [&Pattern.MatchResult] String)`.

Comment (guberathome) [reply core/Pattern.carp]: Sorry, I omited that bit for brevity sake. Here's the complete module:
```
(defmodule Pattern

  (register-type MatchResult "PatternMatchResult" [start Int, end Int])
  (defmodule MatchResult
    (defn refmatch2str [ref-matchres] 
      (fmt "(MatchResult start=%d end=%d)" 
        (MatchResult.start ref-matchres) 
        (MatchResult.end   ref-matchres) ))
    (implements str Pattern.MatchResult.refmatch2str)
    (implements prn Pattern.MatchResult.refmatch2str)
    ;
    (defn match2str [matchres] 
      (Pattern.MatchResult.refmatch2str &matchres) )
    (implements str Pattern.MatchResult.match2str)
    (implements prn Pattern.MatchResult.match2str)
  )
  ; ... code
)
```

Functions look ok from the transcript:
```
> (info Pattern.MatchResult.match2str)
Pattern.MatchResult.match2str : (Fn [Pattern.MatchResult] String)
  Defined at line 14, column 6 in '/home/ptokremin/contrib_ghub/Carp/core/Pattern.carp'
  Implements: (prn str)
> (info Pattern.MatchResult.refmatch2str)
Pattern.MatchResult.refmatch2str : (Fn [(Ref Pattern.MatchResult a)] String)
  Defined at line 7, column 6 in '/home/ptokremin/contrib_ghub/Carp/core/Pattern.carp'
  Implements: (prn str)
> (Pattern.match    #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
(MatchResult start=12 end=22)
> (Pattern.find-all-matches     #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[Warning] No 'prn' function found with type (Fn [Pattern.MatchResult] String).
carp: Can't find any 'prn' function for member 'Inside array.' of type (Fn [Pattern.MatchResult] String)
CallStack (from HasCallStack):
  error, called at src/ArrayTemplates.hs:634:33 in CarpHask-0.5.1.0-EudeCbDnX8j3pnSP31uN8I:ArrayTemplates
```

Could this be related to nested modules?

Comment (hellerve) [reply core/Pattern.carp]: No, this seems fine now. This might possibly be due to the old array code still looking for a function named `prn` rather than a function marked as implementing `prn`. Maybe @scolsen (who built the `implements` mechanism) has some insight on this?

**Comment by hellerve** [comment]
The rename seems good to me!

File: core/Pattern.carp (hunk 1 above)
Comment (guberathome) [reply core/Pattern.carp]: Ok, the problem is elsewhere. I'll open a separate issue.

**Comment by guberathome** [comment]
done, Pattern.split now works as intended:
```
> (Pattern.global-match-str   #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[@"<do>{cmd1}" @"<trouble>{msg2}"]
> (Pattern.find-all   #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[12 46]
> (Pattern.split   #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[@"Whatever we " @" is going to cause some " @" no matter..."]
> (Pattern.match-all-groups     #"<(.-)>{(.-)}" "Whatever we <do>{cmd1} is going to cause some <trouble>{msg2} no matter...")
[[@"do" @"cmd1"] [@"trouble" @"msg2"]]
```

File: core/Pattern.carp [hunk 2]
```diff
@@ -1,28 +1,80 @@
...
-  (register find (Fn [&Pattern &String] Int))
-  (doc find-all "finds all indices of a pattern in a string.
+  (defn find [pattern data]
+    @(Pattern.MatchResult.start &(Pattern.match pattern data)) )
+  
+  (doc find-all "finds all indices of a pattern in a string. The patterns may _not_ overlap.
 
 Returns `[]` if it doesn’t find a matching pattern.")
-  (register find-all (Fn [&Pattern &String] (Array Int)))
+  ;~ (register find-all (Fn [&Pattern &String] (Array Int)))
```
Comment (eriksvedang) [inline core/Pattern.carp:44]: Remove this line?

File: core/Pattern.carp [hunk 3]
```diff
@@ -1,28 +1,80 @@
...
+
+  (register-type MatchResult "PatternMatchResult" [start Int, end Int])
+  (defmodule MatchResult
+    (defn refmatch2str [ref-matchres] 
+      (fmt "(MatchResult start=%d end=%d)" 
+        (MatchResult.start ref-matchres) 
+        (MatchResult.end   ref-matchres) ))
+    (implements str Pattern.MatchResult.refmatch2str)
+    (implements prn Pattern.MatchResult.refmatch2str)
+    ;
```
Comment (eriksvedang) [inline core/Pattern.carp:13]: Remove ; ?

File: core/Pattern.carp [hunk 4]
```diff
@@ -1,28 +1,80 @@
 (system-include "carp_pattern.h")
 
 (defmodule Pattern
+
+  (register-type MatchResult "PatternMatchResult" [start Int, end Int])
+  (defmodule MatchResult
+    (defn refmatch2str [ref-matchres]
```
Comment (eriksvedang) [inline core/Pattern.carp:7]: I'd prefer "refmatch-to-str". This "2" naming scheme is not something we use anywhere else in core.

**Review by eriksvedang — COMMENTED** [review]
Really nice improvements! Had some nitpicks, but the important parts look great.

File: core/Pattern.carp (hunk 4 above)
Comment (TimDeve) [reply core/Pattern.carp:7]: More idiomatic names would be `match2str` => `str`, `refmatch2str` => `ref-str`. You don't really want to repeat the name of the type while in the associated module.

File: core/Pattern.carp (hunk 2 above)
Comment (guberathome) [reply core/Pattern.carp]: done

File: core/Pattern.carp (hunk 3 above)
Comment (guberathome) [reply core/Pattern.carp]: the trailing ";"? 
It's gone

File: core/Pattern.carp (hunk 4 above)
Comment (guberathome) [reply core/Pattern.carp]: done
