### PR TITLE
fix: #1347 by  ignoring generically typed symbols on printing C

### LINKED ISSUE #1347: carp: Can't emit symbol of generic type: e : a at line 4, column 3 in
```
(Project.config "echo-c" true)

(defn identity [e]
  e)

(defn main []
  (ignore (identity 1)))
```
```
$ carp no.carp -x
carp: Can't emit symbol of generic type: e : a at line 4, column 3 in 'C:/Users/richie/Documents/org/projects/handmade-carp/no.carp'
CallStack (from HasCallStack):
  error, called at src\Emit.hs:210:15 in CarpHask-0.5.3.0-ApN9rIbXYwcLYnQzPVPog2:Emit
```
The below code is fine.
```
(defn identity [e]
  e)

(defn main []
  (ignore (identity 1)))
```

### PR DESCRIPTION
**Pull request by hellerve**
This PR fixes #1347 by ignoring generically typed symbols when we echo C output. That should usually be safe, since the specializations will still be printed when the forms require them.

Cheers

### CODE REVIEW

**Review by scolsen — APPROVED** [review]
Nice!

File: src/Primitives.hs [hunk 1]
```diff
@@ -182,10 +182,15 @@ define hidden ctx qualifiedXObj =
     defineInTypeEnv = pure . fromRight ctx . (insertTypeBinder ctx qpath)
     defineInGlobalEnv :: Binder -> IO Context
     defineInGlobalEnv newBinder =
-      when (projectEchoC (contextProj ctx)) (putStrLn (toC All (Binder emptyMeta annXObj)))
+      when (projectEchoC (contextProj ctx) && canBeEmitted annXObj) (putStrLn (toC All (Binder emptyMeta annXObj)))
         >> case (lookupBinderInGlobalEnv ctx qpath) of
           Left _ -> pure (fromRight ctx (insertInGlobalEnv ctx qpath newBinder))
           Right oldBinder -> redefineExistingBinder oldBinder newBinder
+    canBeEmitted :: XObj -> Bool
```
Comment (eriksvedang) [inline src/Primitives.hs:189]: There is already the function `checkForUnresolvedSymbols` in Emit.hs, would that work instead of defining this new one? (Since that function is much more complicated, I also wonder if it could be simplified, or if this one is too simplistic...)

Comment (hellerve) [reply src/Primitives.hs:189]: Ah, I forgot about that one. It looks a little more robust than my simplistic attempt at rewriting it, so I’ll change the PR to use it!

**Review by eriksvedang — APPROVED** [review]
Awesome!
